export const populateData = [
  {
    name: "Simas Žurauskas",
    email: "simaszurauskas@gmail.com",
    city: "Klaipėda",
    street: "J. Zauerveino g.",
    houseNumber: "5-1",
    zip: "92122",
    status: 0,
    geo: {
      latitude: 55.706882,
      longitude: 21.150016,
    },
    id: "l2xcd5zf754680665",
  },
  {
    name: "Jon Doe",
    email: "sample@mail.com",
    city: "Columbus",
    street: "High",
    houseNumber: "5",
    zip: "fv512fbv",
    status: 2,
    geo: null,
    id: "l2xclcv3419b2c3b9",
  },
  {
    name: "Jane Doe",
    email: "hello@me.com",
    city: "Manchester",
    street: "Cake st.",
    houseNumber: "89",
    zip: "M456PZ",
    status: 1,
    geo: null,
    id: "l2xcmqjtcb651dd6d",
  },
  {
    name: "Brad Pit",
    email: "random@zz.net",
    city: "Dallas",
    street: "Bill street",
    houseNumber: "12-6",
    zip: "58562",
    status: 0,
    geo: {
      latitude: 46.37735,
      longitude: -101.996874,
    },
    id: "l2xcp083a52fa0b1e",
  },
  {
    name: "Simply Bob",
    email: "bob@bob.bob",
    city: "Bob",
    street: "Bob",
    houseNumber: "1-b",
    zip: "b-o-b",
    status: 2,
    geo: null,
    id: "l2xcpvt72dd07cf64",
  },
  {
    name: "Stenlis Joe",
    email: "happy.days@mail.co",
    city: "Kalispell",
    street: "Richison Drive",
    houseNumber: "2905",
    zip: "IP20EH",
    status: 2,
    geo: null,
    id: "l2xcrmzq547cd359a",
  },
  {
    name: "Jugemu Goko no Surikire Kaijar Goko no Surikire",
    email: "email@mail.com",
    city: "Urakawa-cho Urakawa-gun",
    street: "Shimadahommachi, Kita-ku-shi, Minato-ku, Hachioji-shi",
    houseNumber: "356-1097",
    zip: "1485625865",
    status: 1,
    geo: null,
    id: "l2xcy6xrfed6c9496",
  },
];
