name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.13.2-chrome97-ff96
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          browser: chrome

      - name: Persist Next.js build cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('yarn.lock') }}-

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
          wait-on: http://localhost:3000

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to Vercel
        id: deploy-vercel-production
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: "${{ secrets.VERCEL_TOKEN }}"
          vercel-org-id: "${{ secrets.VERCEL_ORG_ID }}"
          vercel-project-id: "${{ secrets.VERCEL_PROJECT_ID }}"
